    - name: Set up Docker BuildxMore actions
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          xosadsky/ros-project
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=branch,suffix={{date '.YYYYMMDD.HHmm'}} # napr `main.20210930.1200`
          type=ref,event=tag
          type=semver,pattern={{version}} # napr pri tagu  `v1.0.0`
          type=semver,pattern={{major}}.{{minor}} # napr `1.0`
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}} # `latest` pre každý komit do main vetvy
    - uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./build/docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}